CREATE TABLE IF NOT EXISTS groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_profile_access (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    profile_id INTEGER NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    UNIQUE(group_id, profile_id)
);

CREATE TABLE IF NOT EXISTS oidc_group_mappings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    oidc_group_name TEXT NOT NULL UNIQUE,
    group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE
);
